FIX Don't exit when a release is not found.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,9 +28,13 @@ runs:
         -X GET https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$TAG \
         -H "Accept: application/vnd.github.v3+json")
         if [[ $RESP_CODE != "200" ]]; then
-          echo "Unable to check release status for tag $TAG - HTTP response code was $RESP_CODE"
-          exit 1
+          RESP_MSG = $(jq .message __response.json)
+          if [[ $RESP_MSG != "Not Found" ]]; then
+            echo "Unable to check release status for tag $TAG - HTTP response code was $RESP_CODE"
+            exit 1
+          fi
         fi
+
         RELEASE_ID=$(jq .id __response.json)
         if [[ $RELEASE_ID != "null" ]]; then
           echo "Found an existing release for tag $TAG"
